# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Iain McLaren'
#tagline:          red flag
tagline:          ''
#description:      '<a href="http://iainmclaren.com">red flag</a>'
description:      ''
url:              http://iainmclaren.com
baseurl:          '/'
paginate:         1

author:
  name:           'Iain McLaren'
  url:            https://twitter.com/iainfm

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/imclaren/imclaren.github.io

gems:
  - jekyll-sitemap
